<Project Sdk="Microsoft.NET.Sdk">

	<!-- Import tModLoader mod properties -->
	<Import Project="..\tModLoader.targets" />

	<!-- General -->
	<PropertyGroup>
		
	</PropertyGroup>
	<ItemGroup>
	  <Folder Include="Localization\zh-Hans\" />
	  <Folder Include="Localization\ru-RU\" />
	  <Folder Include="Removed\Sounds\Music\" />
	</ItemGroup>

	<!-- References -->

</Project>