<Project Sdk="Microsoft.NET.Sdk">

	<!-- Import tModLoader mod properties -->
	<Import Project="..\tModLoader.targets" />

	<!-- General -->
	<PropertyGroup>
		
	</PropertyGroup>
	<ItemGroup>
	  <Folder Include="_Content\Snow\World\Tiles\" />
	  <Folder Include="_Content\Stars\World\Tiles\" />
	</ItemGroup>

	<!-- References -->

</Project>